default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_management_system_development

test:
  <<: *default
  database: hotel_management_system_test

production:
  <<: *default
  database: hotel_management_system_production
  username: hotel_management_system
  password: <%= ENV["HOTEL_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
